### ISSUE TITLE
Oauth Client is not logging out on keycloak

### ISSUE THREAD

**Issue by mbrasil** [eugenp/learn-spring-security#28]
Hello @eugenp,

First of all congratulations on the course, I'm learning a lot.

I'm having a problem logging out in the "oauth-client-end--client". When I'm logged in and I press the logout button, the client logs out locally but not on Keycloak. When I press again in the log in button, I'm still logged in because the session in Keycloak still exists.

I did some research and I found this (https://www.keycloak.org/docs/latest/securing_apps/index.html#_spring_security_adapter) and I was thinking if there is anything missing in the logout code.

Am I doing something wrong?
Thank you for your time.

**Comment by lor6** [comment]
Hi @mbrasil 
Yes, this is the expected behavior of a Client by default. To logout from Keycloak entirely, you’d have to explicitly call the Logout endpoint or API:  https://www.keycloak.org/docs/latest/securing_apps/#logout 
We do plan on adding a bonus lesson to the course on this topic later on.

Also, for course support questions, I suggest using the email: course@baeldung.com as it's checked more often.
